### ISSUE TITLE
Operating system specific, consider docker

### ISSUE THREAD

**Issue by zwelshman** [mngad/pySlither#2]
The recent changes to readme suggest an OS limitation, have you considered containerisation? @mngad

**Comment by mngad** [comment]
I have very little interest in docker at the moment, especially given the iffy performance. The fps is very closely tied to the tracking, the difference between 10 and 15 fps is the difference between it working and not. I will boot up windows and see what the issue is.

**Comment by mngad** [comment]
@zwelshman what problems have you run into?

**Comment by zwelshman** [comment]
I cannot specify the screen capture but I can snap the browser window to the left of the screen and the program picks up the dots and cross. do you mention the fail-safe option to exit - i.e. moving the mouse to a corner of the screen?
